//
// Created by david on 1/26/18.
//

#ifndef SIMULATOR_MOTOR_DRIVER_SIMULATOR_MOTOR_DRIVER_NODE_H
#define SIMULATOR_MOTOR_DRIVER_SIMULATOR_MOTOR_DRIVER_NODE_H


class simulator_motor_driver_node {

};


#endif //SIMULATOR_MOTOR_DRIVER_SIMULATOR_MOTOR_DRIVER_NODE_H
