set(_CATKIN_CURRENT_PACKAGE "vision")
set(vision_VERSION "0.0.0")
set(vision_MAINTAINER "nick <nick@todo.todo>")
set(vision_PACKAGE_FORMAT "1")
set(vision_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(vision_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(vision_BUILDTOOL_DEPENDS "catkin")
set(vision_BUILDTOOL_EXPORT_DEPENDS )
set(vision_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(vision_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(vision_TEST_DEPENDS )
set(vision_DOC_DEPENDS )
set(vision_DEPRECATED "")