## USB port
port: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A505WWCA-if00-port0


##### Calibration ####
### accelerometer
accel_x_min: -259.0
accel_x_max: 255.0
accel_y_min: -255.0
accel_y_max: 248.0
accel_z_min: -290.0
accel_z_max: 232.0

### magnetometer
# standard calibration
magn_x_min: -392.0
magn_x_max: 661.0
magn_y_min: -5590.0
magn_y_max: 496.0
magn_z_min: -505.0
magn_z_max: 474.0

# extended calibration
calibration_magn_use_extended: false
magn_ellipsoid_center: [0, 0, 0]
magn_ellipsoid_transform: [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -26.46
gyro_average_offset_y: 58.35
gyro_average_offset_z: -9.04
